{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dial-adapter-openai.fullname" . }}
  labels:
    {{- include "dial-adapter-openai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dial-adapter-openai.selectorLabels" . | nindent 4 }}
{{- end -}}
